# Default values for schemes.
replicaCount: 1
image: schemes-querier:latest
pullPolicy: IfNotPresent
service:
  name: schemes-querier
  type: NodePort
  externalPort: 80
  internalPort: 80
env:
  IDENTITY_URL: https://identity.midnight-lizard.org
  ELASTIC_SEARCH_SCHEMES_READ_MODEL_INDEX_NAME: ksql-table_read-model_public-schemes
  ELASTIC_SEARCH_SCHEMES_READ_MODEL_TYPE_NAME: schemes-read-model
  ELASTIC_SEARCH_CLIENT_URL: http://ml-es-elasticsearch-client:9200
  ALLOWED_ORIGINS: "\
    https://midnight-lizard.org,\
    https://www.midnight-lizard.org"
